cache: bundler
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.1
    gemfile: gemfiles/activerecord_5.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/activerecord_5.1.gemfile
branches:
  only: master
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.3
gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
script: bundle exec rake spec
