cache: bundler
branches:
  only: master
rvm:
- 2.4
- 2.5
- 2.6
bundler_args: ""
before_install: gem install bundler
gemfile:
- gemfiles/activerecord_4.2.gemfile
- gemfiles/activerecord_5.1.gemfile
- gemfiles/activerecord_5.2.gemfile
script: bundle exec rake spec
